In [1]:
import pandas as pd
import numpy as np

In [2]:
housing=pd.read_csv('train.csv')
housing.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
lables = housing[['SalePrice']]
features =housing.drop(['SalePrice'], axis=1)

In [5]:
features.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [6]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [7]:
lables.head()

   SalePrice
0     208500
1     181500
2     223500
3     140000
4     250000

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(features, lables, test_size=0.2,random_state=42)

In [19]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

# Pipeline for numeric attributes
numeric_pipeline = Pipeline([
    ('median_imputer', SimpleImputer(strategy='median')),
    ('std_scaler', StandardScaler())
])

# Pipline for categorical attributes
categorical_pipeline = Pipeline([
    ('one_hot_encoder',OneHotEncoder())
])

In [29]:
from sklearn import set_config

set_config(display='diagram')

numeric_pipeline

TypeError: set_config() got an unexpected keyword argument 'display'

In [47]:
from sklearn.compose import ColumnTransformer

numeric_attributes = [
    'Id','MSSubClass','OverallQual','OverallCond','YearBuilt','TotalBsmtSF','LowQualFinSF','GrLivArea','Fireplaces','GarageCars','GarageArea','WoodDeckSF','OpenPorchSF','ScreenPorch','PoolArea','LotArea','MoSold','YrSold',
    
]

pipeline = ColumnTransformer([
    ('numerical_transformers', numeric_pipeline, numeric_attributes),
    ('categorical_transformers', categorical_pipeline, ['Neighborhood']),
])

In [48]:
pipeline

ColumnTransformer(n_jobs=None, remainder='drop', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('numerical_transformers',
                                 Pipeline(memory=None,
                                          steps=[('median_imputer',
                                                  SimpleImputer(add_indicator=False,
                                                                copy=True,
                                                                fill_value=None,
                                                                missing_values=nan,
                                                                strategy='median',
                                                                verbose=0)),
                                                 ('std_scaler',
                                                  StandardScaler(copy=True,
                                                                 with_mean=True,
                                                                 with_std...
                                  'LowQualFinSF', 'GrLivArea', 'Fireplaces',
                                  'GarageCars', 'GarageArea', 'WoodDeckSF',
                                  'OpenPorchSF', 'ScreenPorch', 'PoolArea',
                                  'LotArea', 'MoSold', 'YrSold']),
                                ('categorical_transformers',
                                 Pipeline(memory=None,
                                          steps=[('one_hot_encoder',
                                                  OneHotEncoder(categories='auto',
                                                                drop=None,
                                                                dtype=<class 'numpy.float64'>,
                                                                handle_unknown='error',
                                                                sparse=True))],
                                          verbose=False),
                                 ['Neighborhood'])],
                  verbose=False)

In [49]:
pipeline.fit_transform(x_train)[0]

array([-1.11928402, -0.8667643 , -0.82044456,  0.3722173 , -0.45546896,
        0.57261219, -0.11899866, -0.40709315, -0.95859215, -1.05654384,
       -0.86383727,  1.18840233, -0.71435182, -0.27583782, -0.07099284,
       -0.21289571, -0.13341669,  1.65006527,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ])

array([-1.1192840216867437, -0.8667643047469886, -0.8204445578548297,
       0.37221730085603477, -0.4554689634533773, 0.5726121928947197,
       -0.11899866377895676, -0.40709314807972335, -0.9585921495629545,
       -1.056543843657237, -0.8638372713165864, 1.1884023292892827,
       -0.7143518217141828, -0.2758378238577077, -0.07099283776824153,
       -0.21289571021689285, -0.1334166899817642, 1.6500652739221804, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'RL', 70.0,
       'Pave', nan, 'Reg', 'Lvl', 'AllPub', 'Inside', 'Gtl', 'Norm',
       'Norm', '1Fam', '1Story', 1957, 'Gable', 'CompShg', 'MetalSd',
       'MetalSd', 'None', 0.0, 'TA', 'Gd', 'CBlock', 'TA', 'TA', 'No',
       'Rec', 922, 'Unf', 0, 392, 'GasA', 'TA', 'Y', 'SBrkr', 1314, 0, 1,
       0, 1, 0, 3, 1, 'TA', 5, 'Typ', nan, 'Attchd', 1957.0, 'RFn', 'TA',
       'TA', 'Y', 0, 0, nan, nan, nan, 0, 'WD', 'Normal'], dtype=object)

In [50]:
from sklearn.linear_model import LinearRegression

model_pipline = Pipeline([
    ('preprocessing', pipeline),
    ('model', LinearRegression())
    
])

model_pipline

Pipeline(memory=None,
         steps=[('preprocessing',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('numerical_transformers',
                                                  Pipeline(memory=None,
                                                           steps=[('median_imputer',
                                                                   SimpleImputer(add_indicator=False,
                                                                                 copy=True,
                                                                                 fill_value=None,
                                                                                 missing_values=nan,
                                                                                 strategy='median',
                                                                                 verbose=0)),
                                                                  ('std_scaler',
                                                                   Sta...
                                                   'MoSold', 'YrSold']),
                                                 ('categorical_transformers',
                                                  Pipeline(memory=None,
                                                           steps=[('one_hot_encoder',
                                                                   OneHotEncoder(categories='auto',
                                                                                 drop=None,
                                                                                 dtype=<class 'numpy.float64'>,
                                                                                 handle_unknown='error',
                                                                                 sparse=True))],
                                                           verbose=False),
                                                  ['Neighborhood'])],
                                   verbose=False)),
                ('model',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [51]:
model_pipline.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('preprocessing',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('numerical_transformers',
                                                  Pipeline(memory=None,
                                                           steps=[('median_imputer',
                                                                   SimpleImputer(add_indicator=False,
                                                                                 copy=True,
                                                                                 fill_value=None,
                                                                                 missing_values=nan,
                                                                                 strategy='median',
                                                                                 verbose=0)),
                                                                  ('std_scaler',
                                                                   Sta...
                                                   'MoSold', 'YrSold']),
                                                 ('categorical_transformers',
                                                  Pipeline(memory=None,
                                                           steps=[('one_hot_encoder',
                                                                   OneHotEncoder(categories='auto',
                                                                                 drop=None,
                                                                                 dtype=<class 'numpy.float64'>,
                                                                                 handle_unknown='error',
                                                                                 sparse=True))],
                                                           verbose=False),
                                                  ['Neighborhood'])],
                                   verbose=False)),
                ('model',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [52]:
model_pipline.predict(x_test)

array([[156599.09535474],
       [326900.14354589],
       [122925.06913566],
       [189751.16850766],
       [271819.75384879],
       [ 55652.33135245],
       [250930.4264786 ],
       [144496.62937448],
       [ 48397.48121179],
       [153183.63819444],
       [161145.02916239],
       [113140.30466762],
       [ 90318.78709414],
       [266405.53479366],
       [184005.79245694],
       [121498.06057809],
       [203083.58709731],
       [130244.30874702],
       [116932.59699253],
       [209885.85017822],
       [166111.08891125],
       [226458.00410754],
       [181846.31214126],
       [126149.77995263],
       [199600.50128797],
       [145425.12299075],
       [191937.71579952],
       [102057.2219096 ],
       [179482.20221571],
       [201583.05300423],
       [132717.07588992],
       [301130.01898139],
       [233000.161624  ],
       [106987.60650016],
       [264492.43640841],
       [158210.00501435],
       [138540.17393696],
       [220654.79348572],
       [336434.12139093],
       [ 94576.87108533],
       [151629.02039861],
       [225167.57935761],
       [113045.21825941],
       [327584.6054405 ],
       [122165.39769171],
       [130727.24439278],
       [104504.81920552],
       [127305.95102727],
       [368850.51101357],
       [128015.75290696],
       [117439.60571621],
       [197589.03865309],
       [121778.73442984],
       [296720.90954548],
       [143774.86100291],
       [228710.73989602],
       [204836.27561136],
       [144383.98917802],
       [146851.23753229],
       [109821.14516333],
       [ 72576.76653563],
       [143164.81410417],
       [332710.9635808 ],
       [260797.07830188],
       [263531.81902392],
       [208023.37995   ],
       [103116.29518222],
       [282842.28076059],
       [112559.1699514 ],
       [172644.990152  ],
       [132761.41965893],
       [131262.13590847],
       [ 96870.67466656],
       [ 61712.34375067],
       [368987.63585143],
       [175276.99086269],
       [314441.47836689],
       [306933.45066885],
       [125669.48280382],
       [131980.12779975],
       [120003.70876527],
       [ 78203.321992  ],
       [127856.27076524],
       [105646.99052809],
       [173220.33166819],
       [136426.30583981],
       [267915.32925214],
       [196501.33217914],
       [143852.35701307],
       [196381.56083401],
       [155222.38413131],
       [144016.34674098],
       [128170.79831442],
       [253778.32749405],
       [124239.01454318],
       [181807.65724597],
       [184822.92277646],
       [179824.81485517],
       [217920.32460719],
       [233919.26509268],
       [182907.24818552],
       [204155.70348037],
       [257236.1323773 ],
       [153316.56688656],
       [212150.45536821],
       [176624.57535711],
       [164978.00238894],
       [274975.88972625],
       [147863.75136098],
       [191822.46525378],
       [ 37074.67616386],
       [117799.14006877],
       [136153.03464729],
       [137245.59106527],
       [213266.5203097 ],
       [116497.85953964],
       [101205.10656715],
       [129767.47722686],
       [165059.32615689],
       [315568.26838347],
       [122434.42892691],
       [146644.09757217],
       [179929.62773652],
       [196775.6011747 ],
       [195951.74874203],
       [121675.44714466],
       [231731.71998247],
       [106351.6902416 ],
       [155364.21759665],
       [191463.62832361],
       [193900.70042483],
       [291062.82679428],
       [210299.83534398],
       [145280.03948359],
       [ 27267.34133193],
       [340655.02749175],
       [310365.42793497],
       [132970.53390334],
       [228389.9464906 ],
       [472923.71627965],
       [337161.57493199],
       [126958.44678526],
       [185226.12867082],
       [168728.79797121],
       [110298.35012368],
       [103695.70320283],
       [239401.08929607],
       [205161.39251774],
       [122765.926123  ],
       [ 25964.77616712],
       [121421.39052828],
       [154976.78059092],
       [260980.65084557],
       [173890.29673974],
       [ 76241.40824714],
       [128423.68878095],
       [116197.29727101],
       [162483.27767334],
       [ 53133.4715378 ],
       [137714.2503779 ],
       [210202.00878858],
       [142688.10960541],
       [260142.87749804],
       [152430.51961624],
       [109587.5607484 ],
       [124753.03633988],
       [243381.46670001],
       [281271.25749177],
       [387542.81579928],
       [236447.26847677],
       [350573.02072087],
       [ 80030.5966162 ],
       [109102.46850174],
       [140771.10272927],
       [329752.48910729],
       [141172.67246506],
       [133157.89714316],
       [221398.23687214],
       [121092.04603352],
       [171778.20670802],
       [152255.96111749],
       [122470.06583494],
       [122975.64406039],
       [167575.70069341],
       [240376.35041056],
       [160707.78528913],
       [251200.49756515],
       [198223.14933984],
       [242304.95082851],
       [ 83575.74532314],
       [117899.42763799],
       [ 98072.37185462],
       [165078.93659436],
       [147805.07418246],
       [226755.39568284],
       [171022.46197715],
       [206182.28042393],
       [ 80423.63851747],
       [210329.275746  ],
       [148064.64889465],
       [249854.52032423],
       [194692.89260564],
       [115890.77910371],
       [327538.85049982],
       [194912.17505736],
       [101044.05357611],
       [229816.42539548],
       [139556.47664628],
       [154659.33308156],
       [105568.06642949],
       [235896.2700069 ],
       [165680.15251069],
       [108604.64625808],
       [168214.11386459],
       [228125.84507202],
       [247811.72394898],
       [195665.17749806],
       [121934.24781227],
       [128553.39961654],
       [140969.79289848],
       [138895.25291307],
       [253928.71888051],
       [212303.41810968],
       [105340.02703175],
       [239473.22663647],
       [163467.66828082],
       [ 88318.9732323 ],
       [ 82910.60848344],
       [168394.73266071],
       [ 93850.18516614],
       [ 91245.01848443],
       [174894.22413198],
       [124027.35083164],
       [118295.98235274],
       [226059.61915775],
       [147870.44080883],
       [192000.65859151],
       [148564.36924525],
       [227914.77300411],
       [119103.92935762],
       [125994.7772301 ],
       [258158.68153691],
       [218733.00148038],
       [395232.58263759],
       [178526.2595826 ],
       [ 74934.71955127],
       [141298.31115523],
       [188044.00027948],
       [144643.21249931],
       [ 94688.34365663],
       [186676.47889954],
       [178730.37906315],
       [130937.73321564],
       [ 81167.9533778 ],
       [143636.81106101],
       [145591.63188166],
       [126625.29029757],
       [116084.3037886 ],
       [169511.62210912],
       [237120.74648284],
       [331720.6434505 ],
       [215596.13282171],
       [140025.41935083],
       [218848.71007796],
       [273804.32568335],
       [242368.13722821],
       [153592.22287392],
       [136806.84978777],
       [111791.68492178],
       [181146.79800115],
       [362406.18318983],
       [255399.94083302],
       [241961.70125036],
       [ 92027.17984781],
       [ 98097.51880247],
       [132273.29907655],
       [171330.4423938 ],
       [300288.05805571],
       [202158.76887089],
       [138066.1868489 ],
       [220363.9602328 ],
       [ 69280.22226048],
       [209844.48109242],
       [109839.53065275],
       [257256.33736122],
       [176915.37710012],
       [209629.37057133],
       [116461.82870197],
       [288420.9799979 ],
       [194585.1642311 ],
       [106612.0324957 ],
       [118240.4166539 ]])

In [57]:
from sklearn.metrics import mean_squared_error, r2_score

predictions = model_pipline.predict(x_test)
rmse = mean_squared_error(y_test, predictions, squared=False)
r2 = r2_score(y_test, predictions)
print(f'RMSE: {rmse}')
print(f'R-squared: {r2}')

RMSE: 34270.5306591398
R-squared: 0.846881444160933